package com.zte.ums.an.uni.dsl.conf.cdf.collect.parser.dataprocess;

/**
 * <p>文件名称:SubCollectXmlContent.java</p>
 * <p>文件描述: </p>
 * <p>版权所有: 版权所有(C)2001-2013</p>
 * <p>公    司: 中兴通讯股份有限公司</p>
 * <p>内容摘要: </p>
 * <p>其他说明: </p>
 * <p>完成日期: 2012-7-9</p>
 * <p>修改记录1:</p>
 * <pre>
 *    修改日期：
 *    版 本 号：
 *    修 改 人：
 *    修改内容：
 * </pre>
 * <p>修改记录2：</p>
 * @version 1.0
 * @author ChenDuoduo_10087118
 */
public class SubCollectXmlContent
{
    public static final String subCollectXml = "<?xml version=\"1.0\" encoding=\"GBK\"?>\r\n"
               + "<Server>\r\n"
               + "    <!-- Fill in sub-collect server parameters here. -->\r\n"
               + "    <Sub_Server>\r\n"
               + "        <Alias>Sub-Server1</Alias>\r\n"
               + "        <!-- Server name to help for remembering, free to configure. -->\r\n"
               + "        <Server_IP></Server_IP>\r\n"
               + "        <!-- Real IP or host name of sub-collect server.-->\r\n"
               + "        <Scheduled_Period>15</Scheduled_Period>\r\n"
               + "        <!-- NOT SUGGEST to change. Means the period to requst task from dispatch server if needed. unit: seconds. -->\r\n"
               + "        <Heart_Beat>5</Heart_Beat>\r\n"
               + "        <!-- MUST NOT change. Heart beat period to dispatch server, also related to report generating. unit: seconds -->\r\n"
               + "        <NE_Type_Filter>ZXDSL9836</NE_Type_Filter>\r\n"
               + "        <!-- MUST NOT change -->\r\n"
               + "        <Reduce_IO>true</Reduce_IO>\r\n"
               + "        <!-- NOT SUGGEST to change. If true, memory operation will be increase.-->\r\n"
               + "        <Delete_PreFiles>true</Delete_PreFiles>\r\n"
               + "        <!-- MUST NOT change. Only for debug purpose -->\r\n"
               + "    </Sub_Server>\r\n"
               + "    <!-- Fill in database parameters here. This database is used for collecting performance data. "
               + "MUST execute conf/install-db.bat(sh) first. -->\r\n"
               + "    <Database>\r\n"
               + "        <DbType>oracle</DbType>\r\n"
               + "        <!-- Opions: oracle, mssql -->\r\n"
               + "        <Port>1521</Port>\r\n"
               + "        <!-- Mostly, 1521 for oracle, 1433 for mssql. -->\r\n"
               + "        <Server_Ip></Server_Ip>\r\n"
               + "        <Super_User></Super_User>\r\n"
               + "        <Super_User_Password></Super_User_Password>\r\n"
               + "        <DbName>uep</DbName>\r\n"
               + "        <!-- DO NOT change. Fixed oracle SID, no use for mssql.-->\r\n"
               + "        <Max_Connect>10</Max_Connect>\r\n"
               + "        <!-- NOT SUGGEST to change. -->\r\n"
               + "    </Database>\r\n"
               + "    <!-- Fill in remote dispatch server parameters here. -->\r\n"
               + "    <Remote_Dispatch_Server>\r\n"
               + "        <Server_IP></Server_IP>\r\n"
               + "        <!-- MUST be consistent with Server_IP in cdf-dispatch.xml -->\r\n"
               + "        <Server_Port>12346</Server_Port>\r\n"
               + "        <!-- MUST be consistent with Server_Port in cdf-dispatch.xml -->\r\n"
               + "        <Remote_Object_Name>DispatchService</Remote_Object_Name>\r\n"
               + "        <!-- MUST be consistent with Remote_Object_Name in cdf-dispatch.xml -->\r\n"
               + "    </Remote_Dispatch_Server>\r\n"
               + "    <!-- Fill in FTP parameters here. The FTP must be local and must have writing permission.  -->\r\n"
               + "    <FTP>\r\n" + "        <Server_IP></Server_IP>\r\n"
               + "        <!-- Real IP of local host, MUST NOT be 127.0.0.1 -->\r\n" + "        <User></User>\r\n"
               + "        <Password></Password>\r\n" + "        <Main_Dir></Main_Dir>\r\n"
               + "        <!-- FTP Root Directory -->\r\n" + "    </FTP>\r\n"
               + "    <!-- NOT SUGGEST to change -->\r\n" + "    <Thread>\r\n"
               + "        <Thread_Num>300</Thread_Num>\r\n" + "        <!-- Very important to perfomance -->\r\n"
               + "        <Pool_Reinitial_Time>3600</Pool_Reinitial_Time>\r\n"
               + "        <!-- unit: Seconds -->\r\n" + "    </Thread>\r\n"
               + "    <!-- NOT SUGGEST to change -->\r\n" + "    <SNMP>\r\n" + "        <Timeout>5</Timeout>\r\n"
               + "        <!-- unit: Seconds -->\r\n" + "        <Retries>2</Retries>\r\n" + "    </SNMP>\r\n"
               + "    <!-- NOT SUGGEST to change -->\r\n" + "    <Fast_SNMP>\r\n"
               + "        <Timeout>2</Timeout>\r\n" + "        <!-- unit: Seconds -->\r\n"
               + "        <Retries>0</Retries>\r\n" + "    </Fast_SNMP>\r\n" + "    <!-- MUST NOT change -->\r\n"
               + "    <BulkPool_Validation>\r\n" + "        <Time_Tolerance>60</Time_Tolerance>\r\n"
               + "    </BulkPool_Validation>\r\n" + "</Server>";

    public static final String subCollectDataXml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n"
               + "\r\n"
               + "<Server>\r\n"
               + "    <!-- MUST NOT change -->\r\n"
               + "    <BulkPool_Validation>\r\n"
               + "        \r\n"
               + "        <Group name=\"USERPORT\">\r\n"
               + "            <fixedArea>\r\n"
               + "                <Field>getMoc</Field>\r\n"
               + "                <Field>getName</Field>\r\n"
               + "            </fixedArea>\r\n"
               + "        \r\n"
               + "            <merge>\r\n"
               + "                <BulkPool name=\"USERPORT(ALL)\"/>\r\n"
               + "                <BulkPool name=\"USERPORT(LINE)\"/>\r\n"
               + "                <BulkPool name=\"USERPORT(CHANNEL)\" readProxy=\"com.zte.ums.an.uni.dsl.conf.cdf"
               + ".collect.parser.bufferreader.DoubleLineBufferedReader\"/>\r\n"
               + "            </merge>\r\n"
               + "            <append> <!-- Optional -->\r\n"
               + "                <BulkPool name=\"testUserPortPort\" readProxy=\"com.zte.ums.an.uni.dsl.conf.cdf.collect.parser"
               + ".bufferreader.DoubleLineBufferedReader\">\r\n"
               + "                    <AppendInfo indexMerge=\"1\" indexAppend=\"87\" valueAppend=\"1,2\"/>\r\n"
               + "                </BulkPool>\r\n"
               + "            </append>\r\n"
               + "        </Group>\r\n"
               + "        \r\n"
               + "        <Group name=\"TESTSimple\">\r\n"
               + "            <merge>\r\n"
               + "                <BulkPool name=\"KPNTEST11\" readProxy=\"java.io.BufferedReader\"/>\r\n"
               + "                <BulkPool name=\"KPNTEST22\" readProxy=\"java.io.BufferedReader\">\r\n"
               + "                    <AppendInfo indexMerge=\"1\" indexAppend=\"0\"/>\r\n"
               + "                </BulkPool>\r\n"
               + "            </merge>    \r\n"
               + "        </Group>\r\n"
               + "        \r\n"
               + "        <Group name=\"TESTDoubleLine\">\r\n"
               + "            <merge>\r\n"
               + "                <BulkPool name=\"KPNDoubleLine000\" />\r\n"
               + "                <BulkPool name=\"KPNDoubleLine111\" />        \r\n"
               + "                <BulkPool name=\"KPNDoubleLine222\" readProxy=\"com.zte.ums.an.uni.dsl.conf.cdf.collect.parser.bufferreader."
               + "DoubleLineBufferedReader\" />\r\n" + "            </merge> \r\n" + "        </Group>\r\n"
               + "        \r\n" + "        <Group name=\"TESTAppend\">\r\n" + "            <merge>\r\n"
               + "                <BulkPool name=\"KPN111\" />        \r\n" + "            </merge> \r\n"
               + "            <append>\r\n" + "                <BulkPool name=\"KPNAppend111\">\r\n"
               + "                    <AppendInfo indexMerge=\"1\" indexAppend=\"0\" valueAppend=\"1,2\"/>\r\n"
               + "                </BulkPool>\r\n" + "                <BulkPool name=\"KPNAppend222\">\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"1\"/>\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"2\"/>\r\n"
               + "                </BulkPool>\r\n" + "            </append>\r\n" + "        </Group>\r\n"


               // Test one filter
               + "        <Group name=\"TESTOneFilter\">\r\n"
               + "            <merge>\r\n"
               + "                <BulkPool name=\"OneFilterMerge111\" />        \r\n" 
               + "            </merge> \r\n"
               + "            <append>\r\n" 
               + "                <BulkPool name=\"OneFilterMerge222\">\r\n"
               + "                    <AppendInfo indexMerge=\"1\" indexAppend=\"0\" valueAppend=\"1,2\"/>\r\n"
               + "                </BulkPool>\r\n" 
               + "                <BulkPool name=\"OneFilterMerge333\">\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"1\"/>\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"2\"/>\r\n"
               + "                </BulkPool>\r\n" 
               + "            </append>\r\n"
               + "            <filter>\r\n"
               + "                  <FilterInfo indexFilter=\"5\" valueFilter=\"AA1_From_APPFile\" />\r\n"
               + "            </filter>\r\n"
               + "        </Group>\r\n"
               
               // Test multi-filter and the filter value is many
               + "        <Group name=\"TESTMultiFilter\">\r\n"
               + "            <merge>\r\n"
               + "                <BulkPool name=\"MultiFilterMerge111\" />        \r\n" 
               + "            </merge> \r\n"
               + "            <append>\r\n" 
               + "                <BulkPool name=\"MultiFilterMerge222\">\r\n"
               + "                    <AppendInfo indexMerge=\"1\" indexAppend=\"0\" valueAppend=\"1,2\"/>\r\n"
               + "                </BulkPool>\r\n" 
               + "                <BulkPool name=\"MultiFilterMerge333\">\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"1\"/>\r\n"
               + "                    <AppendInfo indexMerge=\"2\" indexAppend=\"0\" valueAppend=\"2\"/>\r\n"
               + "                </BulkPool>\r\n" 
               + "            </append>\r\n"
               + "            <filter>\r\n"
               + "                  <FilterInfo indexFilter=\"4\" valueFilter=\"WishesString\" />\r\n"
               + "                  <FilterInfo indexFilter=\"5\" valueFilter=\"InputString,AA1_From_APPFile\" />\r\n"
               + "            </filter>\r\n"
               + "        </Group>\r\n"
               
               + "    </BulkPool_Validation>\r\n" + "</Server>";
}
